# Generated by Django 5.0.3 on 2024-03-23 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=256, verbose_name='Электронная почта')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('phone_number', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('/^\\+?(\\d{1,3})?[- .]?\\(?(?:\\d{2,3})\\)?[- .]?\\d{3}?\\d{3}$/')])),
                ('photosession_type', models.CharField(choices=[('1', 'Портрет.'), ('2', 'Фотоссестия Пары (Love Story).'), ('3', 'Репортаж.'), ('4', 'Fashion.'), ('5', 'Предметная Фотография.'), ('6', 'Пейзаж.'), ('7', 'Архитектурная Фотография.'), ('8', 'Стиль "ню".'), ('9', 'Фотографии детей.'), ('10', 'Съёмка домашних животных или диких животных.'), ('11', 'Свадебная фотосессия.'), ('12', 'Фотосъёмка беременных.'), ('13', 'Макросъёмка.')], default='1', max_length=64, verbose_name='Тип фотосессии')),
                ('example', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Примеры')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=256, unique=True, verbose_name='Имя Пользователя')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=256, validators=[django.core.validators.MinLengthValidator(8, 'Пароль должен быть не меньше 8 символов'), django.core.validators.MaxLengthValidator(256, 'Пароль должен быть не более 256 символов')])),
                ('user_type', models.CharField(choices=[('1', 'Клиент'), ('2', 'Фотограф')], max_length=64, verbose_name='Тип Пользователя')),
                ('agreement', models.BooleanField(verbose_name='Соглашение')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(verbose_name='Текст')),
                ('likes', models.IntegerField(default=0, verbose_name='Лайки')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photosessionapp.user', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='Электронная почта')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('surname', models.CharField(max_length=256, verbose_name='Фамилия')),
                ('photo', models.ImageField(height_field=750, upload_to='', verbose_name='Фотография', width_field=750)),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('tech', models.CharField(blank=True, max_length=256, null=True, verbose_name='Техника')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photosessionapp.user', verbose_name='Пользователь')),
            ],
        ),
    ]
