# Generated by Django 5.0.3 on 2024-03-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosessionapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Клиент'), ('2', 'Фотограф')], default='1', max_length=64, verbose_name='Тип Пользователя'),
        ),
    ]
