# Generated by Django 5.0.3 on 2024-03-28 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosessionapp', '0002_alter_photographer_user_id_alter_review_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='photograph_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='photosessionapp.photographer', verbose_name='Фотограф'),
            preserve_default=False,
        ),
    ]
