# Generated by Django 5.0.3 on 2024-03-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photosessionapp', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agreement',
        ),
    ]
