# Generated by Django 5.0.3 on 2024-03-30 11:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosessionapp', '0003_reservation_photograph_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'Рассматривается'), ('2', 'Одобрена'), ('0', 'Отклонена')], default='1', max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='description',
            field=models.TextField(null=True, verbose_name='* Описание'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.CharField(blank=True, max_length=256, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('/^\\+?(\\d{1,3})?[- .]?\\(?(?:\\d{2,3})\\)?[- .]?\\d{3}?\\d{3}$/')], verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='photograph_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photosessionapp.photographer', verbose_name='* Фотограф'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='photosession_type',
            field=models.CharField(choices=[('1', 'Портрет.'), ('2', 'Фотоссестия Пары (Love Story).'), ('3', 'Репортаж.'), ('4', 'Fashion.'), ('5', 'Предметная Фотография.'), ('6', 'Пейзаж.'), ('7', 'Архитектурная Фотография.'), ('8', 'Стиль "ню".'), ('9', 'Фотографии детей.'), ('10', 'Съёмка домашних животных или диких животных.'), ('11', 'Свадебная фотосессия.'), ('12', 'Фотосъёмка беременных.'), ('13', 'Макросъёмка.')], default='1', max_length=64, verbose_name='* Тип фотосессии'),
        ),
    ]
