# Generated by Django 5.0.3 on 2024-04-02 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosessionapp', '0004_reservation_status_alter_reservation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photographer',
            name='work_days',
            field=models.CharField(choices=[('Понедельник', 'понедельник'), ('Вторник', 'вторник'), ('Среда', 'среда'), ('Четверг', 'четверг'), ('Пятница', 'пятница'), ('Суббота', 'суббота'), ('Воскресенье', 'воскресенье')], default=0, max_length=16, verbose_name='Рабочие дни'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photosessionapp.photographer', verbose_name='Пользователь'),
        ),
    ]
