# Generated by Django 5.0.3 on 2024-04-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photosessionapp', '0005_photographer_work_days_alter_review_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='photographer',
            name='work_days',
            field=models.CharField(max_length=128, verbose_name='Рабочие дни'),
        ),
    ]
